In [9]:
import heapq
import numpy as np
from collections import deque, Counter

## Knapsack Problem

In [64]:
def knapsack_bottomup(weights, values, capacity):
    n = len(weights)
    V = [[0 for _ in range(capacity+1)] for _ in range(n+1)]
    for i in range(1, n+1):
        for j in range(1, capacity+1):
            if weights[i-1] <= j:
                V[i][j] = max(V[i-1][j], values[i-1] + V[i-1][j-weights[i-1]])
            else:
                V[i][j] = V[i-1][j]
                
    print(np.array(V))
#     print()
#     print('weights:', end=' ')
#     result = V[n][capacity]
#     w = capacity
#     i = n
#     while i > 0 and result > 0:
#         if result != V[i-1][w]:
#             print(weights[i-1], end=' ')
            
#             result -= values[i-1]
#             w = w - weights[i-1]
#         i -= 1
    
    return V[n][capacity]
            

In [65]:
weights = [1, 2, 4, 2, 5]
values = [5, 3, 5, 3, 2]

knapsack_bottomup(weights, values, capacity=10)

[[ 0  0  0  0  0  0  0  0  0  0  0]
 [ 0  5  5  5  5  5  5  5  5  5  5]
 [ 0  5  5  8  8  8  8  8  8  8  8]
 [ 0  5  5  8  8 10 10 13 13 13 13]
 [ 0  5  5  8  8 11 11 13 13 16 16]
 [ 0  5  5  8  8 11 11 13 13 16 16]]


16

In [40]:
cache = dict()
def knapsack_n(weights, values, idx, capacity, path=[]):
    key = (idx, capacity)
    if key in cache:
        return cache[key]
    
    if idx < 0 or capacity == 0:
        result = 0
    elif weights[idx] > capacity:
        result = knapsack_n(weights, values, idx - 1, capacity, path)
    else:
        a = knapsack_n(weights, values, idx - 1, capacity)
        b = values[idx] + knapsack_n(weights, values, idx - 1, capacity - weights[idx], path)
        result = max(a, b)
    
    cache[key] = result
    
    return result

In [41]:
weights = [1, 2, 4, 2, 5]
values = [5, 3, 5, 3, 2]
path = []

knapsack_n(weights, values, len(weights)-1, 10, path)

16

In [47]:
def knapsack(weights):
    w_sum = sum(weights)
    possible = {i: 0 for i in range(w_sum)}
    possible[0] = 1
    
    for k in weights:
        for x in reversed(range(w_sum)):
            if possible[x]:
                possible[x + k] = 1
                
    return possible

In [48]:
weights = [1, 3, 3, 5]

knapsack(weights)

{0: 1,
 1: 1,
 2: 0,
 3: 1,
 4: 1,
 5: 1,
 6: 1,
 7: 1,
 8: 1,
 9: 1,
 10: 0,
 11: 1,
 12: 1}

In [49]:
weights = [1, 3, 3, 5]
possible = {i: 0 for i in range(sum(weights))}
possible[0] = 1
possible

{0: 1, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0, 10: 0, 11: 0}

In [12]:
sum(weights)

12

In [13]:
list(reversed(range(sum(weights))))

[11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [14]:
for k in weights:
    for x in reversed(range(sum(weights))):
        if possible[x]:
            possible[x + k] = 1
possible

{0: 1,
 1: 1,
 2: 0,
 3: 1,
 4: 1,
 5: 1,
 6: 1,
 7: 1,
 8: 1,
 9: 1,
 10: 0,
 11: 1,
 12: 1}

In [ ]:
0, 1, 3, 4, 5, 6, 7, 8, 9, 11, 12

In [ ]:
1, 4, 6, 7, 9, 12

In [4]:
#backtrack solution to solving n queens on an nxn chessboard
n = 4
count = [0]
column = [0 for _ in range(n)]
diag1 = [0 for _ in range(2*n-1)]
diag2 = [0 for _ in range(2*n-1)]

def q_search(y):
    if y == n:
        count[0] += 1
        return
    for x in range(n):
        if column[x] or diag1[x+y] or diag2[x-y+n-1]: continue
        column[x] = diag1[x+y] = diag2[x-y+n-1] = 1
        q_search(y+1)
        column[x] = diag1[x+y] = diag2[x-y+n-1] = 0

In [5]:
q_search(0)
print(count[0])

2


In [8]:
for i in range(n):
    for j in range(n):
        print(i-j+n-1)

3
2
1
0
4
3
2
1
5
4
3
2
6
5
4
3


In [7]:
def valid(xs):
    cnt = 0
    for x in xs:
        if x == '(':
            cnt += 1
        else:
            cnt -=1
            if cnt < 0:
                return False
            
    return cnt == 0

In [8]:
xs = '((()))'
xs = '(()())'
xs = '()())'
xs = '))(('

valid(xs)

False

In [9]:
width, remainder = divmod(10, 3)
width, remainder

(3, 1)

In [12]:
width + (0 < remainder)

4

In [21]:
h = []
nums = [1, 1, 1, 2, 2, 2, 3, 3, 4, 5, 5, 5, 5]

counts = Counter(nums)
counts

Counter({1: 3, 2: 3, 3: 2, 4: 1, 5: 4})

In [22]:
for n in nums:
    heapq.heappush(h, n)

In [23]:
h

[1, 1, 1, 2, 2, 2, 3, 3, 4, 5, 5, 5, 5]

In [20]:
h

[2, 2, 3, 3, 5, 5, 5, 5, 4]

In [19]:
heapq.heappop(h)

2

In [4]:
n = 5
board = [['.'] * n for _ in range(n)]

board

[['.', '.', '.', '.', '.'],
 ['.', '.', '.', '.', '.'],
 ['.', '.', '.', '.', '.'],
 ['.', '.', '.', '.', '.'],
 ['.', '.', '.', '.', '.']]

In [8]:
board = np.array([['.', '.', 'Q', '.'], ['Q', '.', '.', '.'], ['.', '.', '.', 'Q'], ['.', 'Q', '.', '.']])

for o in board:
    print(''.join(o))

..Q.
Q...
...Q
.Q..


In [4]:
q = deque([3, 2, 4])

print(q.popleft())

print(q)
q.extendleft(reversed([5, 6]))

print(q)

3
deque([2, 4])
deque([5, 6, 2, 4])


In [6]:
list(q)

[5, 6, 2, 4]

In [3]:
q = deque([[3]])
q

deque([[3]])

In [9]:
q.popleft()

[3]

In [10]:
q

deque([])

In [7]:
xs = [1, 2, 3, 4, 5]
xs[:2], xs[2:]

([1, 2], [3, 4, 5])

# Top K Largest

In [1]:
def partition(nums, left, right):
    pivot = nums[right]
    idx = left
    for i in range(left, right):
        if nums[i] <= pivot:
            nums[i], nums[idx] = nums[idx], nums[i]
            idx += 1

    nums[idx], nums[right] = nums[right], nums[idx]
    
    return idx
    
def find_k_largest(nums, k):
    n = len(nums)
    left = 0
    right = n - 1
    
    while left <= right:
        pivot_idx = partition(nums, left, right)
        print('pivot idx', pivot_idx, 'left', left, 'right', right)
        
        if pivot_idx == n - k:
            return nums[pivot_idx]
        elif pivot_idx > n - k:
            right = pivot_idx - 1
        else:
            left = pivot_idx + 1 
            
    return -1

In [2]:
# nums = [5, 7, 2, 3, 4, 1, 6]
nums = [5, 7, 2, 3, 4, 1, 0]

find_k_largest(nums, 5)

pivot idx 0 left 0 right 6
pivot idx 5 left 1 right 6
pivot idx 1 left 1 right 4
pivot idx 2 left 2 right 4


2

# Flatten a binary tree to a doubly linked list in-place

                1
        2                3
    4        5        6        7

`return 4 <-> 2 <-> 5 <-> 1 <-> 6 <-> 3 <-> 7`

In [10]:
class Node:
    
    def __init__(self, val):
        self.val = val
        self.left = None
        self.right = None
        self.prev = None
        self.next = None
        
        
def traverse(node):
    curr = node
    while curr:
        print(curr.val)
        curr = curr.next

In [19]:
root = Node(1)
root.left = Node(2)
root.left.left = Node(4)
root.left.right = Node(5)
root.right = Node(3)
root.right.left = Node(6)
root.right.right = Node(7)

In [20]:
def convert_to_dll(node):
    if node is None: return
    
    global prev, head
    
    convert_to_dll(node.left)
    
    if prev is None:
        head = node
    else:
        node.prev = prev
        prev.next = node
    
    prev = node
    
    convert_to_dll(node.right)
    

In [21]:
prev = None
head = None

convert_to_dll(root)
head.val

4

In [22]:
head

In [23]:
traverse(head)

4
2
5
1
6
3
7


# Duplicate String

In [17]:
s = 'Java'

counts = dict()
for c in s:
    counts[c] = counts.get(c, 0) + 1
    
counts

{'J': 1, 'a': 2, 'v': 1}

In [18]:
max_count = -1
for k, v in counts.items():
    if v > max_count and v > 1:
        max_count = v
        char = k

In [19]:
char, max_count

('a', 2)

# Check Parindrome

In [20]:

def parindrom(s):
    n = len(s)
    for i in range(n // 2):
        if s[i] != s[n-i-1]:
            return False
        
    return True
        

In [21]:
s1 = 'abba'
s2 = 'abbc'

parindrom(s1)

True

In [22]:
parindrom(s2)

False

In [23]:
parindrom('radar')

True

In [24]:
parindrom('a')

True

# print first non repeated character from String

In [25]:
def first_non_repeat(s):
    counts = dict()
    for c in s:
        counts[c] = counts.get(c, 0) + 1
        
    for c in s:
        count = counts[c]
        if count == 1:
            print(c)
            break
        

In [26]:
first_non_repeat('Morning')

M


# Reverse String

In [36]:
def reverse(s):
    if s == '':
        return ''
    return reverse(s[1:]) + s[0]

def reverse_iter(s):
    n = len(s)
    xs = list(s)
    for i in range(n//2):
        xs[i], xs[n-i-1] = xs[n-i-1], xs[i]
        
    return ''.join(xs)
        

In [37]:
reverse('string')

'gnirts'

In [38]:
reverse_iter('string')

'gnirts'

21) How to find the length of the longest substring with K distinct characters?
Write a program to find out the length of the longest substring in it with no more than K distinct characters.
Input: String="araaci", K=2
Output: 4
Explanation: The longest substring with no more than '2' distinct characters is "araa".

Tip: You can solve this problem using a sliding window pattern as discussed in the Smallest Subarray with a given sum. You can also use a HashMap to remember the frequency of each character we have processed.  If you are not familiar with the sliding window pattern then I also suggest you check out Grokking the Coding Interview: Patterns for Coding Questions course on Educative.

It's an interactive and one of its kind courses to learn about essential coding interview patterns like Sliding Window, Merge Interval, Fast and Slow pointer, etc which you can use to solve hundreds fo coding problems on an interview.

Read more: https://javarevisited.blogspot.com/2015/01/top-20-string-coding-interview-question-programming-interview.html#ixzz6RyeauWLi

# All Substrings

In [39]:
def allsubstr(x):
    n = len(x)
    for i in range(n):  
        for j in range(i, n):  
            print(x[i:j+1])

In [40]:
allsubstr('abc')

a
ab
abc
b
bc
c


In [59]:
def subsets(idx, xs, curr):
    print(curr)
    for i in range(idx, len(xs)):
        curr.append(xs[i])
        subsets(i+1, xs, curr)
        curr.pop()

In [60]:
s = list('abc')
s

['a', 'b', 'c']

In [61]:
subsets(0, s, [])

[]
['a']
['a', 'b']
['a', 'b', 'c']
['a', 'c']
['b']
['b', 'c']
['c']


# All Permutations

In [4]:
def permute(perm, xs, chosen):
    n = len(xs)
    if n == len(perm):
        print(perm)
    else:
        for i in range(n):
            if chosen[i]: continue
            perm.append(xs[i])
            chosen[i] = True
            permute(perm, xs, chosen)
            chosen[i] = False
            perm.pop()

In [7]:
permute([], 'abc', [False, False, False])

['a', 'b', 'c']
['a', 'c', 'b']
['b', 'a', 'c']
['b', 'c', 'a']
['c', 'a', 'b']
['c', 'b', 'a']


In [1]:
def _permute(perm, x):
    if x:
        n = len(x)
        for i in range(n):
            _permute(perm + x[i], x[0:i] + x[i+1:n])
    else:
        print(perm)

def permute(x):
    _permute("", x)
        

In [2]:
permute('abc')

abc
acb
bac
bca
cab
cba


In [3]:
permute('xyz')

xyz
xzy
yxz
yzx
zxy
zyx


In [72]:
'abc'[1:]

'bc'

# Sort LinkedList using MergeSort

In [32]:
class Node:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next
        
def traverse(head):
    curr = head
    while curr:
        print(curr.val, end=' ')
        curr = curr.next
    print()
    
def merge(l1, l2):
    
    if l1 is None: return l2
    if l2 is None: return l1
    
    if l1.val <= l2.val:
        l1.next = merge(l1.next, l2)
        return l1
    else:
        l2.next = merge(l1, l2.next)
        return l2

def front_back_split(head):
    if not head or not head.next:
        return head
    
    backward = head
    forward = head.next
    
    while forward:
        forward = forward.next
        if forward:
            backward = backward.next
            forward = forward.next
    
    tmp = backward.next
    backward.next = None
    backward = tmp
    return head, backward

def merge_sort(head):
    if not head or not head.next:
        return head
    
    a, b = front_back_split(head)
    a = merge_sort(a)
    b = merge_sort(b)
    
    return merge(a, b)

In [33]:
arr = [10, 4, 15, 1, 2, 12, 54, 0, 21, 9]

head = None
for i in reversed(arr):
    head = Node(i, head)
    
traverse(head)

10 4 15 1 2 12 54 0 21 9 


In [34]:
l = merge_sort(head)
traverse(l)

0 1 2 4 9 10 12 15 21 54 


In [47]:
def merge_iter(a, b):
    p = a
    q = b
    dummy_head = Node(0)
    curr = dummy_head
    
    while True:
        if not p:
            curr.next = q
            break
        if not q:
            curr.next = p
            break
            
        if p.val <= q.val:
            curr.next = p
            p = p.next
        else:
            curr.next = q
            q = q.next
            
        curr = curr.next
        
    return dummy_head.next

In [48]:
l1 = l2 = None

for i in reversed([1, 3]):
    l1 = Node(i, l1)
    
for i in reversed([2, 4]):
    l2 = Node(i, l2)
    

In [49]:
head = merge_iter(l1, l2)
traverse(head)

1 2 3 4 


In [31]:
head = merge(l1, l2)
traverse(head)

1 2 3 4 


In [43]:
l = merge_sort(head)
traverse(l)

10 4 12 15 1 2 54 0 21 9 


In [50]:
first, second = front_back_split(head)

In [51]:
traverse(first)

1 2 


In [52]:
traverse(second)

3 4 


# Maximum Sub-array Sum (MSS)

In [53]:
def mcs(arr, l, m, h):
    """maximum crossing sum"""
    right_sum = left_sum = float('-inf')
    sum_ = 0
    for i in range(m, l-1, -1):
        sum_ += arr[i]
        left_sum = max(left_sum, sum_)
        
    sum_ = 0
    for i in range(m+1, h+1):
        sum_ += arr[i]
        right_sum = max(right_sum, sum_)
        
    return max(left_sum + right_sum, left_sum, right_sum)
    
    
def mss(arr, l, h):
    """maximum sub-array"""
    if l == h:
        return arr[l]
    
    m = (l + h) // 2
    left_mss = mss(arr, l, m)
    right_mss = mss(arr, m+1, h)
    crossing_mcs = mcs(arr, l, m, h)
        
    return max(left_mss, right_mss, crossing_mcs)

In [54]:
arr = [2, 3, 4, 5, 7] 
n = len(arr) 
  
max_sum = mss(arr, 0, n-1)
max_sum

21

In [55]:
arr = [-2, 1, -3, 4, -1, 2, 1, -5, 4]
mss(arr, 0, len(arr)-1)

6

In [73]:
def factorial(a):
    i = 1
    res = 1
    while i <= a:
        res = res * i
        i += 1
        
    return res

In [74]:
factorial(4)

24

In [75]:
# Return the number of pairs with  
# equal values. 
def countPairs(arr, n): 
  
    mp = dict() 
  
    # Finding frequency of each number. 
    for i in range(n): 
        if arr[i] in mp.keys(): 
            mp[arr[i]] += 1
        else: 
            mp[arr[i]] = 1
              
    # Calculating pairs of each value. 
    ans = 0
    for it in mp: 
        count = mp[it]
        ans += factorial(count) // (2 * factorial(count - 2))
#         ans += (count * (count - 1)) // 2
        
    print(mp)
    return ans

In [76]:
arr = [1, 1, 2] 
n = len(arr) 
print(countPairs(arr, n)) 

{1: 2, 2: 1}
1


In [77]:
arr = [1, 1, 1, 1, 1, 2] 
n = len(arr) 
print(countPairs(arr, n)) 

{1: 5, 2: 1}
10


In [82]:
def maxSubArray(nums):
    """
    :type nums: List[int]
    :rtype: int
    """
    dp = [0 for i in range(len(nums))]
    dp[0] = nums[0]
    for i in range(1,len(nums)):
        dp[i] = max(dp[i-1]+nums[i],nums[i])
        #print(dp)
    return max(dp)


In [83]:
nums = [-2,1,-3,7,-2,2,1,-5,4]

maxSubArray(nums)

8

In [84]:
maxSubArray([-2, -3, 4, -1, -2, 1, 5, -3])

7

In [85]:
arr = [-2, 1, -3, 4, -1, 2, 1, -5, 4]
maxSubArray(arr)

6

# Longest Palindromic Substring

In [86]:
st = "forgeeksskeegfor"
# st = "abacdb"
# st = "cbbd"

n = len(st)
DP = [[0 for x in range(n)] for y in range(n)]

# All substrings of length 1 are 
# palindromes 
max_len = 1
start = 0

In [87]:
# base case
i = 0
for i in range(n):
    DP[i][i] = True
    
np.array(DP)

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [88]:
# base case

for i in range(n-1):
    if st[i] == st[i+1]:
        DP[i][i+1] = True
        start = i
        max_len = 2

print(list(st))
np.array(DP)

['f', 'o', 'r', 'g', 'e', 'e', 'k', 's', 's', 'k', 'e', 'e', 'g', 'f', 'o', 'r']


array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [89]:
start

10

In [90]:
n

16

In [91]:
for k in range(3, n+1):
    print(n-k+1)
    for i in range(n-k+1):
        j = i + k - 1
        print('(i, j)', i, j)
        if st[i] == st[j] and DP[i+1][j-1]:
            DP[i][j] = True
            
            if k > max_len:
                start = i
                max_len = k
            
        j += 1

14
(i, j) 0 2
(i, j) 1 3
(i, j) 2 4
(i, j) 3 5
(i, j) 4 6
(i, j) 5 7
(i, j) 6 8
(i, j) 7 9
(i, j) 8 10
(i, j) 9 11
(i, j) 10 12
(i, j) 11 13
(i, j) 12 14
(i, j) 13 15
13
(i, j) 0 3
(i, j) 1 4
(i, j) 2 5
(i, j) 3 6
(i, j) 4 7
(i, j) 5 8
(i, j) 6 9
(i, j) 7 10
(i, j) 8 11
(i, j) 9 12
(i, j) 10 13
(i, j) 11 14
(i, j) 12 15
12
(i, j) 0 4
(i, j) 1 5
(i, j) 2 6
(i, j) 3 7
(i, j) 4 8
(i, j) 5 9
(i, j) 6 10
(i, j) 7 11
(i, j) 8 12
(i, j) 9 13
(i, j) 10 14
(i, j) 11 15
11
(i, j) 0 5
(i, j) 1 6
(i, j) 2 7
(i, j) 3 8
(i, j) 4 9
(i, j) 5 10
(i, j) 6 11
(i, j) 7 12
(i, j) 8 13
(i, j) 9 14
(i, j) 10 15
10
(i, j) 0 6
(i, j) 1 7
(i, j) 2 8
(i, j) 3 9
(i, j) 4 10
(i, j) 5 11
(i, j) 6 12
(i, j) 7 13
(i, j) 8 14
(i, j) 9 15
9
(i, j) 0 7
(i, j) 1 8
(i, j) 2 9
(i, j) 3 10
(i, j) 4 11
(i, j) 5 12
(i, j) 6 13
(i, j) 7 14
(i, j) 8 15
8
(i, j) 0 8
(i, j) 1 9
(i, j) 2 10
(i, j) 3 11
(i, j) 4 12
(i, j) 5 13
(i, j) 6 14
(i, j) 7 15
7
(i, j) 0 9
(i, j) 1 10
(i, j) 2 11
(i, j) 3 12
(i, j) 4 13
(i, j) 5 14
(i, j) 6 

In [92]:
start, max_len

(3, 10)

In [93]:
st[start:start+max_len]

'geeksskeeg'

In [94]:
DP

[[True, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, True, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, True, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, True, 0, 0, 0, 0, 0, 0, 0, 0, True, 0, 0, 0],
 [0, 0, 0, 0, True, True, 0, 0, 0, 0, 0, True, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, True, 0, 0, 0, 0, True, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, True, 0, 0, True, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, True, True, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, True, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, True, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, True, True, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, True, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, True, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, True, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, True, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, True]]

# K-th occurence of item in BST

In [96]:
arr = [2, 4, 10, 10, 10, 18, 20]

def _search(arr, data, low, high):
    result = -1
    while low <= high:
        mid = (low + high) // 2
        if arr[mid] == data:
            result = mid
            low = mid + 1
#             high = mid - 1
        elif data < arr[mid]:
            high = mid - 1
        elif data > arr[mid]:
            low = mid + 1
            
    return result

def search(arr, data):
    return _search(arr, data, 0, len(arr)-1)
        

In [97]:
search(arr, 2), search(arr, 4), search(arr, 5), search(arr, 10), search(arr, 19), search(arr, 20)

(0, 1, -1, 4, -1, 6)

In [98]:
search(arr, 10)

4

In [99]:
class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next
        
def traverse(head):
    curr = head
    while curr:
        print(curr.val, end=' ')
        curr = curr.next
    print()
        
def merge_list(l1: ListNode, l2: ListNode) -> ListNode:
    if l1 is None:
        return l2
    if l2 is None:
        return l1

    if l1.val < l2.val:
        l1.next = merge_list(l1.next, l2)
        return l1
    else:
        l2.next = merge_list(l1, l2.next)
        return l2
    
def merge_list_loop(p, q):
    
    dummy_head = ListNode(0)
    tail = dummy_head
    
    while True:
        
        if q is None:
            tail.next = p
            break
        if p is None:
            tail.next = q
            break
        
        if p.val < q.val:
            tail.next = p
            p = p.next
        else:
            tail.next = q
            q = q.next
            
            
        tail = tail.next
    
    return dummy_head.next
        

In [105]:
l1 = None
l2 = None

for i in reversed([1, 2, 4]):
    l1 = ListNode(i, l1)
    
for i in reversed([1, 3, 4]):
    l2 = ListNode(i, l2)
    
traverse(l1), traverse(l2)

1 2 4 
1 3 4 


(None, None)

In [104]:
head = merge_list_loop(l1, l2)
traverse(head)

1 1 2 3 4 4 


In [106]:
head = merge_list(l1, l2)
traverse(head)

1 1 2 3 4 4 


In [107]:
def count_pairs(nums, K):
    seen = {}  # seen[val] = idx
    count = 0
    for i, num in enumerate(nums):
        pair = K - num
        seen_count = seen.get(pair, 0)
        if seen_count > 0:
            print(num, pair, 'count=', seen_count)
            count += seen_count
        else:
            seen[num] = seen.get(num, 0) + 1
        print(seen)
    
    return count

In [108]:
# count_pairs([1,1,2,3,4,6,7], 5)
# (2, 3), (0, 4), (1, 4)

In [109]:
count_pairs([1,1,2,3,4,6,7], 5)

{1: 1}
{1: 2}
{1: 2, 2: 1}
3 2 count= 1
{1: 2, 2: 1}
4 1 count= 2
{1: 2, 2: 1}
{1: 2, 2: 1, 6: 1}
{1: 2, 2: 1, 6: 1, 7: 1}


3

In [110]:
count_pairs([7,0,1,1,2,3,4,6,7], 5)

{7: 1}
{7: 1, 0: 1}
{7: 1, 0: 1, 1: 1}
{7: 1, 0: 1, 1: 2}
{7: 1, 0: 1, 1: 2, 2: 1}
3 2 count= 1
{7: 1, 0: 1, 1: 2, 2: 1}
4 1 count= 2
{7: 1, 0: 1, 1: 2, 2: 1}
{7: 1, 0: 1, 1: 2, 2: 1, 6: 1}
{7: 2, 0: 1, 1: 2, 2: 1, 6: 1}


3

# Find count of an element in a sorted list

In [2]:
def _search(arr, data, low, high, occurence='last'):
    result = -1
    while low <= high:
        mid = (low + high) // 2
        if arr[mid] == data:
            result = mid
            if occurence == 'last':
                low = mid + 1
            else:
                high = mid - 1
        elif data < arr[mid]:
            high = mid - 1
        elif data > arr[mid]:
            low = mid + 1
            
    return result

def count_occurrences(arr, data):
    first = _search(arr, data, 0, len(arr)-1, occurence='first')
    if first == -1:
        return -1
    else:
        last = _search(arr, data, 0, len(arr)-1, occurence='last')
    return last - first + 1

In [3]:
arr = [1, 1, 3, 3, 5, 5, 5, 5, 5, 9, 9, 11]

count_occurrences(arr, 5), count_occurrences(arr, 1), count_occurrences(arr, 3), count_occurrences(arr, 11)

(5, 2, 2, 1)

In [4]:
count_occurrences(arr, 0)

-1

# How many times is a sorted array rotated?

#TODO: not done

In [5]:
def rotation_count(arr):
    n = len(arr)
    low = 0
    high = n - 1
    while low <= high:
        if arr[low] <= arr[high]:
            return low
        
        mid = (low + high) // 2
        next_ = (mid + 1) % n
        prev = (mid - 1 + n) % n
        if arr[mid] <= arr[next_] and arr[mid] <= arr[prev]:
            return mid
        
        if arr[mid] <= arr[high]:
            high = mid - 1
        elif arr[mid] >= arr[low]:
            low = mid + 1
    return -1

In [6]:
arr = [11, 12, 15, 18, 2, 5, 6, 8]
# arr = [15, 22, 23, 28, 31, 38, 5, 6, 8, 10, 12]
# arr = [1, 2, 3, 4]
arr = [17, 18, 2, 5, 6, 8]

rotation_count(arr)

2

# Sorted array to BST

In [23]:
class Node: 
    def __init__(self, data):
        self.data = data
        self.left = None
        self.right = None
        
def _array_to_bst(arr, start, end):
    if start <= end:
        mid = (start + end) // 2
        node = Node(arr[mid])
        print(start, mid, end)
        node.left = _array_to_bst(arr, start, mid - 1)
        node.right = _array_to_bst(arr, mid + 1, end)
        return node

def array_to_bst(arr):
    return _array_to_bst(arr, 0, len(arr) - 1)

def preorder(node): 
    if not node: 
        return
    
    print(node.data)
    preorder(node.left)
    preorder(node.right)
    
def inorder(node): 
    if not node: 
        return
    
    inorder(node.left)
    print(node.data)
    inorder(node.right)
    

In [24]:
arr = [1, 2, 3, 4, 5]

head = array_to_bst(arr)
head

0 2 4
0 0 1
1 1 1
3 3 4
4 4 4


In [22]:
inorder(head)

1
2
3
4
5


In [20]:
preorder(head)

3
1
2
4
5


In [10]:
arr = sorted([6, 2, 3, 4, 5, 2, 1])

head = array_to_bst(arr)
head

In [11]:
inorder(head)

1
2
2
3
4
5
6


# Sorted Linked List to BST

In [12]:
class TNode: 
    def __init__(self, data):
        self.data = data
        self.left = None
        self.right = None
        
class LNode:
    def __init__(self, data):
        self.data = data
        self.next = None
        
def lpush(head, data):
    node = LNode(data)
    node.next = head
    head = node
    return head

def ltraverse(head):
    current = head
    while current:
        print(current.data)
        current = current.next

def lcount(head):
    current = head
    cnt = 0
    while current:
        cnt += 1
        current = current.next
    return cnt

def inorder(node): 
    if not node: 
        return
    
    inorder(node.left)
    print(node.data)
    inorder(node.right)

In [13]:
head = None

head = lpush(head, 5)
head = lpush(head, 4)
head = lpush(head, 3)
head = lpush(head, 2)
head = lpush(head, 1)

ltraverse(head)

n = lcount(head)
n

1
2
3
4
5


5

In [103]:
def ll_to_bst(head, start, end):
    def _ll_to_bst(start, end):
        nonlocal head
        if start <= end:
            mid = start + (end - start) // 2
            left = _ll_to_bst(start, mid - 1)
            print('data', head.data, 'start', start, 'end', end, 'mid', mid)
            node = TNode(head.data)
            node.left = left
            head = head.next
            node.right = _ll_to_bst(mid + 1, end)
            return node
    return _ll_to_bst(start, end)
    

In [104]:
h = ll_to_bst(head, 0, n-1)

data 1 start 0 end 1 mid 0
data 2 start 1 end 1 mid 1
data 3 start 0 end 4 mid 2
data 4 start 3 end 4 mid 3
data 5 start 4 end 4 mid 4


In [105]:
inorder(h)

1
2
3
4
5


In [106]:
h.left.data

1

In [107]:
ltraverse(head)

1
2
3
4
5


# Count the number of Islands

In [14]:
data = [[1, 1, 0, 0, 0],
       [0, 1, 0, 0, 1],
       [1, 0, 0, 1, 1],
       [0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1]]

data

[[1, 1, 0, 0, 0],
 [0, 1, 0, 0, 1],
 [1, 0, 0, 1, 1],
 [0, 0, 0, 0, 0],
 [1, 0, 1, 0, 1]]

In [15]:
len(data), len(data[0])

(5, 5)

In [16]:
def _mark_island(i, j, data):
    n_rows = len(data)
    n_cols = len(data[0])
    
    if i >= 0 and i < n_rows and j >= 0 and j < n_cols and data[i][j] == 1:
        data[i][j] = -1 # mark as visited
        _mark_island(i+1, j, data) # right
        _mark_island(i-1, j, data) # left
        _mark_island(i, j-1, data) # top
        _mark_island(i, j+1, data) # bottom

def count_island(data):
    count = 0
    for i in range(len(data)):
        for j in range(len(data[0])):
            if data[i][j] == 1:
                _mark_island(i, j, data)
                count += 1
                
    return count
                
    

In [17]:
count_island(data)

6

In [18]:
data

[[-1, -1, 0, 0, 0],
 [0, -1, 0, 0, -1],
 [-1, 0, 0, -1, -1],
 [0, 0, 0, 0, 0],
 [-1, 0, -1, 0, -1]]

# 2Sum

In [19]:
def two_sum(nums, x):
    snums = sorted(nums)
    
    i = j = 0
    j = len(snums) - 1
    found = False
    while i < j:
        if snums[i] + snums[j] > x:
            j -= 1
        elif snums[i] + snums[j] < x:
            i += 1
        else:
            print(snums[i], snums[j])
            i += 1
            found = True
            
    if not found:
        print(-1)
        

In [20]:
nums = [0, -1, 2, -3, 1, 2]

In [21]:
two_sum(nums, -1)

-3 2
-1 0


In [22]:
nums.sort()

In [23]:
nums

[-3, -1, 0, 1, 2, 2]

# 3Sum

In [24]:
def three_sum(nums, x):
    snums = sorted(nums)
    n = len(snums)
    
    i = 0
    while i < n - 1:
        l = i + 1
        r = n - 1
        
        while l < r:
            sum_ = snums[i] + snums[l] + snums[r]
            if sum_ > x:
                r -= 1
            elif sum_ < x:
                l += 1
            else:
                print(snums[i], snums[l], snums[r])
                l += 1
                r -= 1
                
        i += 1
        

In [25]:
# nums = [12, 3, 4, 1, 6, 9]
nums = [0, -1, 2, -3, 1]

three_sum(nums, 0) # 12, 3, 9

-3 1 2
-1 0 1


In [26]:
sorted(nums)

[-3, -1, 0, 1, 2]

# Max Profit with K Transactions

In [27]:
def profit(prices, k):
    
    if not len(prices):
        return 0
    
    profits = [[0 for d in range(len(prices))] for t in range(k + 1)]
    
    for t in range(1, k + 1):
        max_so_far = float('-inf')
        for d in range(1, len(prices)):
            max_so_far = max(max_so_far, profits[t-1][d-1] - prices[d - 1])
            profits[t][d] = max(profits[t][d-1], max_so_far + prices[d])
            
    return profits[-1][-1]
            
    
    

In [28]:
prices = [5, 11, 3, 50, 60, 90]

profit(prices, 2)

93

# Cheapest Flights Within K Stops

In [29]:
from collections import deque, defaultdict

In [30]:
def find_cheapest_price(n, flights, src, dst, K):
    
    adj_list = defaultdict(list)
    for src, dst, price in flights:
        adj_list[src].append((dst, price))
        
    visited = {src: 0} # city: minimum price to get here
    q = deque([(src, 0, 0)])
    # BFS start with src
    # q : (city, curPrice, curStops)
    
    while q:
        curr, price, stops = q.popleft()
        for new_city, cost in adj_list[curr]:
            if new_city not in visited or cost + price < visited[new_city]:
                if stops < K:
                    q.append((new_city, cost + price, stops + 1))
                    
                visited[new_city] = cost + price
    
    return visited.get(dst, -1)


In [31]:
n = 3
flights = [[0, 1, 100], [1, 2, 100], [0, 2, 500]]
src = 0
dst = 2
k = 1

find_cheapest_price(n, flights, src, dst, k)

200

In [32]:
n = 3
flights = [[0, 1, 100], [1, 2, 100], [0, 2, 500]]
src = 0
dst = 2
k = 0

find_cheapest_price(n, flights, src, dst, k)

500

In [2]:
xs = [1, 2, 3, 4]

In [3]:
xs.pop()

4

In [4]:
xs

[1, 2, 3]

In [5]:
sum([])

0

In [2]:
xs = [[1, 2, 3], [4, 5, 6]]

[1, 2, 3] in xs

True

In [3]:
sorted([10,1,2,7,6,1,5])

[1, 1, 2, 5, 6, 7, 10]